#!/usr/bin/env ruby

#
# copyright 2009 by Nik Wolfgramm
# all rights reserved
# 

# resolve the application path
libdir = File.dirname( (File.readlink(__FILE__) rescue File.dirname(__FILE__)) )
$LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)

require 'lib/runner'

command = ARGV[0]

#begin
  MySqlMb::Runner.new(ARGV).run command
#rescue StandardError => e
#  puts e.message
#  exit 0
#end
