#!/usr/bin/env ruby

#
# copyright 2010 by Nik Wolfgramm
# all rights reserved
# 

# resolve the application path
appdir = File.symlink?(__FILE__) ?
		File.dirname(File.readlink(__FILE__)) :
                File.dirname(__FILE__)
libdir = File.expand_path(appdir, "/../lib")
$LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)

#require appdir + '/lib/runner'
require 'lib/runner'

command = ARGV[0]

#begin
  MySqlMb::Runner.new( MySqlMb::Config.new(ARGV) ).run command
#rescue StandardError => e
#  puts e.message
#  exit 0
#end
